eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
gateway:
  ip: 127.0.0.1
server:
  port: ${PORT:0}
spring:
  application:
    name: users-ws
  datasource:
    password: Password@1234
    url: jdbc:mysql://localhost:3306/hr
    username: user1
  devtools:
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
